### ISSUE TITLE
Mixing up field types: class org.elasticsearch.index.mapper.core.StringFieldMapper$StringFieldType != class org.elasticsearch.index.mapper.geo.BaseGeoPointFieldMapper$GeoPointFieldType

### ISSUE THREAD

**Issue by jyotiskab** [TargetHolding/pyspark-elastic#11]
The issue is that I have defined "coord" as a geopoint index type as follows:

{
    "mappings": {
        "map_doc": {
            "dynamic": true,
            "properties": {
                "coord": {
                    "type": "geo_point"
                }
           }
     } 
}

In my python code I have the following:
es_entries['coord'] = str(json_data['_latitude_'])+","+str(json_data['_longitude_'])

I have represented the geo_point as an acceptable string representation. "json_data" is a python dictionary. Unfortunately, I'm unable to invoke "saveToEs(rdd)" and get the following error:

**Caused by: org.apache.spark.util.TaskCompletionListenerException: Found unrecoverable error [xxx.xxx.xxx.xxx:9200] returned Bad Request(400) - failed to parse;Mixing up field types: class org.elasticsearch.index.mapper.core.StringFieldMapper$StringFieldType != class org.elasticsearch.index.mapper.geo.BaseGeoPointFieldMapper$GeoPointFieldType on field coord; Bailing out..**

**Comment by jyotiskab** [comment]
Nevermind, I made a silly spelling error. I am able to index the geo_point fields now. There is nothing unexpected or wrong with this library in regards to indexing geo_point fields

**Comment by sihu168** [comment]
我这里还不行，可以帮我解决吗？
